import * as React from 'react';
import { useMemo } from 'react';
export const data = [
    {
      col1: 'bill',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'betty',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'anne',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'george',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'alice',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'mike',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'jessica',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'ferdenand',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'beatrice',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'bobby',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'bovine',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'gertie',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'frank',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'wanda',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'art',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'amber',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
    {
      col1: 'josh',
      col2: 'team 1',
      col3: '40',
      col4: '8',
      col5: 'America/Chicago',
      col6: 'Y',
      col7: 'Icon',
    },
  ]
