export const holidays = [
  { label : 'Angola', value: 'AO' },
  { label : 'Argentina', value: 'AR' },
  { label : 'Aruba', value: 'AW' },
  { label : 'Australia', value: 'AU' },
  { label : 'Austria', value: 'AT' },
  { label : 'Bangladesh', value: 'BD' },
  { label : 'Belarus', value: 'BY' },
  { label : 'Belgium', value: 'BE' },
  { label : 'Botswana', value: 'BW' },
  { label : 'Brazil', value: 'BR' },
  { label : 'Bulgaria', value: 'BG' },
  { label : 'Burundi', value: 'BI' },
  { label : 'Canada', value: 'CA' },
  { label : 'Chile', value: 'CL' },
  { label : 'Colombia', value: 'CO' },
  { label : 'Croatia', value: 'HR' },
  { label : 'Curacao', value: 'CW' },
  { label : 'Czechia', value: 'CZ' },
  { label : 'Denmark', value: 'DK' },
  { label : 'Djibouti', value: 'DJ' },
  { label : 'Dominican Republic', value: 'DO' },
  { label : 'Egypt', value: 'EG' },
  { label : 'England', value: 'GB' },
  { label : 'Estonia', value: 'EE' },
  { label : 'European Central Bank	', value: 'ECB' },
  { label : 'Finland', value: 'FI' },
  { label : 'France', value: 'FR' },
  { label : 'Georgia', value: 'GE' },
  { label : 'Germany', value: 'DE' },
  { label : 'Greece', value: 'GR' },
  { label : 'Honduras', value: 'HN' },
  { label : 'Hong Kong', value: 'HK' },
  { label : 'Hungary', value: 'HU' },
  { label : 'Iceland', value: 'IS' },
  { label : 'India', value: 'IN' },
  { label : 'Ireland', value: 'IE' },
  { label : 'Isle Of Man', value: 'GB' },
  { label : 'Israel', value: 'IL' },
  { label : 'Italy', value: 'IT' },
  { label : 'Jamaica', value: 'JM' },
  { label : 'Japan', value: 'JP' },
  { label : 'Kenya', value: 'KE' },
  { label : 'Korea', value: 'KR' },
  { label : 'Latvia', value: 'LV' },
  { label : 'Lithuania', value: 'LT' },
  { label : 'Luxembourg', value: 'LU' },
  { label : 'Malaysia', value: 'MY' },
  { label : 'Malawi', value: 'MW' },
  { label : 'Mexico', value: 'MX' },
  { label : 'Morocco', value: 'MA' },
  { label : 'Mozambique', value: 'MZ' },
  { label : 'Netherlands', value: 'NL' },
  { label : 'New Zealand', value: 'NZ' },
  { label : 'Nicaragua', value: 'NI' },
  { label : 'Nigeria', value: 'NG' },
  { label : 'Northern Ireland', value: 'GB' },
  { label : 'Norway', value: 'NO' },
  { label : 'Paraguay', value: 'PY' },
  { label : 'Peru', value: 'PE' },
  { label : 'Poland', value: 'PL' },
  { label : 'Portugal', value: 'PT' },
  { label : 'Portugal Ext', value: 'PTE' },
  { label : 'Romania', value: 'RO' },
  { label : 'Russia', value: 'RU' },
  { label : 'Saudi Arabia', value: 'SA' },
  { label : 'Scotland', value: 'GB' },
  { label : 'Serbia', value: 'RS' },
  { label : 'Singapore', value: 'SG' },
  { label : 'Slovakia', value: 'SK' },
  { label : 'Slovenia', value: 'SI' },
  { label : 'South Africa', value: 'ZA' },
  { label : 'Spain', value: 'ES' },
  { label : 'Sweden', value: 'SE' },
  { label : 'Switzerland', value: 'CH' },
  { label : 'Turkey', value: 'TR' },
  { label : 'Ukraine', value: 'UA' },
  { label : 'United Arab Emirates', value: 'AE' },
  { label : 'United Kingdom', value: 'GB' },
  { label : 'United States', value: 'US' },
  { label : 'Venezuela', value: 'YV' },
  { label : 'Vietnam', value: 'VN' },
  { label : 'Wales', value: 'GB' },
] ;