import { DashboardSetting } from 'settings/types';

export const dashboardOverview: DashboardSetting = {
  id: 'overview-dashboard',
  name: 'Overview Dashboard',
  enabled: true,
  dropdownIndex: '0',
  widgets: [
    {
      id: 'title-widget1',
      type: 'label',
      presentation: { show: true, text: 'All Interactions' },
      sizeX: 30,
      sizeY: 1,
      col: 1,
      row: 1,
    },
    {
      id: 'widget1',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'active-interactions-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Active Interactions' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 1,
      row: 2,
    },
    {
      id: 'widget2',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'interaction-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg. Interaction Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 2,
    },
    {
      id: 'widget3',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'interaction-starts-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Total Interactions Today' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 5,
    },
    {
      id: 'widget4',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-satisfaction-score',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'CSAT' },
        value: { format: 'percent' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 2,
    },
    {
      id: 'widget5',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'interactions-in-conversation-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'In Conversation' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 2,
    },
    {
      id: 'widget6',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'conversation-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg. Conversation Duration' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 2,
    },
    {
      id: 'widget7',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'abandons-before-queue-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'IVR Abandons' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 26,
      row: 2,
    },
    {
      id: 'widget8',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandons-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Queue Abandons' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 26,
      row: 5,
    },
    {
      id: 'source-switcher1',
      type: 'source-switcher',
      entity: 'queue',
      presentation: { title: { show: true, text: 'Queue' } },
      sizeX: 15,
      sizeY: 2,
      minSizeX: 10,
      minSizeY: 1,
      col: 1,
      row: 10,
    },
    {
      id: 'widget9',
      type: 'gauge',
      query: {
        api: 'realtime-statistics',
        endpoint: 'service-level',
        responseKey: 'percent',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: false, text: '' },
        value: { format: 'percent' },
        gaugeConfig: {
          data: {
            columns: [['data', 0]],
            type: 'gauge',
            colors: { data: '#777' },
          },
          gauge: {
            label: { show: false },
            units: '%',
            min: 0,
            max: 100,
          },
          tooltip: { show: false },
          color: {
            data: '#ffffff',
            pattern: ['#ff0000', '#f6c600', '#0aad36'],
            threshold: { values: [70, 80, 100] },
          },
          legend: { show: false },
          size: {},
        },
        footer: { show: true, text: 'Answered within SLA' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 1,
      row: 12,
    },
    {
      id: 'widget10',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-length',
        responseKey: 'count',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'In Queue' },
        value: { format: 'count' },
        footer: { show: false, text: 'customers' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 12,
    },
    {
      id: 'widget11',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandons-count',
        responseKey: 'count',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Queue Abandons' },
        value: { format: 'count' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 15,
    },
    {
      id: 'widget12',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'avg',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Avg. Queue Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 12,
    },
    {
      id: 'widget13',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-satisfaction-score',
        responseKey: 'percent',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'CSAT' },
        value: { format: 'percent' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 15,
    },
    {
      id: 'title-widget3',
      type: 'label',
      presentation: { show: true, text: 'All Agents' },
      sizeX: 20,
      sizeY: 1,
      col: 17,
      row: 10,
    },
    {
      id: 'widget14',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-logged-in-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Logged In' },
        value: { format: 'count' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 17,
      row: 12,
    },
    {
      id: 'widget15',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-idle-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Idle' },
        value: { format: 'count' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 22,
      row: 12,
    },
    {
      id: 'widget16',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-idle-percentage',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Idle %' },
        value: { format: 'percent' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 22,
      row: 15,
    },
    {
      id: 'widget17',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-away-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Away' },
        value: { format: 'count' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 27,
      row: 12,
    },
    {
      id: 'widget18',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-away-percentage',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Away %' },
        value: { format: 'percent' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 27,
      row: 15,
    },
    {
      id: 'widget19',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-busy-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Busy' },
        value: { format: 'count' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 32,
      row: 12,
    },
    {
      id: 'widget20',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-busy-percentage',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Busy %' },
        value: { format: 'percent' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 32,
      row: 15,
    },
  ],
};
