import { DashboardSetting } from 'settings/types';

export const dashboardInteractions: DashboardSetting = {
  id: 'interactions-dashboard',
  name: 'Interactions Dashboard',
  enabled: true,
  dropdownIndex: '10',
  widgets: [
    {
      id: 'title-widget1',
      type: 'label',
      presentation: { show: true, text: 'All Interactions' },
      sizeX: 34,
      sizeY: 1,
      col: 3,
      row: 1,
    },
    {
      id: 'widget1',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-satisfaction-score',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'CSAT' },
        value: { format: 'percent' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 3,
      row: 2,
    },
    {
      id: 'widget2',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'active-interactions-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Active Interactions' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 9,
      row: 2,
    },
    {
      id: 'widget3',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'interaction-starts-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Total Interactions Today' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 15,
      row: 2,
    },
    {
      id: 'widget4',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'abandons-before-queue-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'IVR Abandons' },
        value: { format: 'count' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 15,
      row: 8,
    },
    {
      id: 'widget5',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'interaction-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Interaction Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 2,
    },
    {
      id: 'widget6',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandons-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Queue Abandons' },
        value: { format: 'count' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 8,
    },
    {
      id: 'widget7',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-holds-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Customer Holds' },
        value: { format: 'count' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 6,
      col: 27,
      row: 2,
    },
    {
      id: 'widget8',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'consult-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Consult Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 27,
      row: 8,
    },
    {
      id: 'widget9',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-hold-time',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Agent Holds' },
        value: { format: 'count' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 32,
      row: 2,
    },
    {
      id: 'widget10',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-hold-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Customer Hold Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 32,
      row: 5,
    },
    {
      id: 'widget11',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-initiated-customer-hold-time',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Agent Initiated Customer Holds' },
        value: { format: 'count' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 32,
      row: 8,
    },
    {
      id: 'title-widget2',
      type: 'label',
      presentation: { show: true, text: 'In Conversation Interactions' },
      sizeX: 10,
      sizeY: 1,
      col: 3,
      row: 12,
    },
    {
      id: 'widget12',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'interactions-in-conversation-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'In Conversation' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 3,
      row: 13,
    },
    {
      id: 'widget13',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'conversation-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg In Conversation Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 8,
      row: 13,
    },
    {
      id: 'widget14',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'conversation-time',
        responseKey: 'min',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Min In Conversation Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 3,
      row: 16,
    },
    {
      id: 'widget15',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'conversation-time',
        responseKey: 'max',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Max In Conversation Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 8,
      row: 16,
    },
    {
      id: 'title-widget3',
      type: 'label',
      presentation: { show: true, text: 'In Queue Interactions' },
      sizeX: 10,
      sizeY: 1,
      col: 15,
      row: 12,
    },
    {
      id: 'widget16',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-length',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'In Queue' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 15,
      row: 13,
    },
    {
      id: 'widget17',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'min',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Min Queue Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 20,
      row: 13,
    },
    {
      id: 'widget18',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Queue Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 15,
      row: 16,
    },
    {
      id: 'widget19',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'max',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Max Queue Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 20,
      row: 13,
    },
    {
      id: 'title-widget4',
      type: 'label',
      presentation: { show: true, text: 'In Routing Interactions' },
      sizeX: 10,
      sizeY: 1,
      col: 27,
      row: 12,
    },
    {
      id: 'widget20',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'interactions-in-routing-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'In Routing' },
        value: { format: 'count' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 27,
      row: 13,
    },
    {
      id: 'widget21',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'routing-time',
        responseKey: 'min',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Min In Routing Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 32,
      row: 13,
    },
    {
      id: 'widget22',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'routing-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg In Routing Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 27,
      row: 16,
    },
    {
      id: 'widget23',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'routing-time',
        responseKey: 'max',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Max In Routing Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 32,
      row: 16,
    },
  ],
};
