import { DashboardSetting } from 'settings/types';

export const dashboardResources: DashboardSetting = {
  id: 'resources-dashboard',
  name: 'Resources Dashboard',
  enabled: true,
  dropdownIndex: '30',
  widgets: [
    {
      id: 'widget1',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-idle-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Idle' },
        value: { format: 'count' },
        footer: { show: false, text: 'Ready Resources' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 1,
      row: 1,
    },
    {
      id: 'widget2',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-away-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Away' },
        value: { format: 'count' },
        footer: { show: false, text: 'Resources Away' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 1,
    },
    {
      id: 'widget3',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-busy-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Busy' },
        value: { format: 'count' },
        footer: { show: false, text: 'Busy Resources' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 1,
    },
    {
      id: 'widget4',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-idle-percentage',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Idle %' },
        value: { format: 'percent' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 1,
      row: 4,
    },
    {
      id: 'widget5',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-away-percentage',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Away %' },
        value: { format: 'percent' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 4,
    },
    {
      id: 'widget6',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-busy-percentage',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Busy %' },
        value: { format: 'percent' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 4,
    },
    {
      id: 'widget7',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-satisfaction-score',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'CSAT' },
        value: { format: 'percent' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 1,
      row: 8,
    },
    {
      id: 'widget8',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resources-logged-in-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Logged In' },
        value: { format: 'count' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 8,
    },
    {
      id: 'widget9',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-talk-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Talk Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 8,
    },
    {
      id: 'widget10',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-wrap-up-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Wrap-up Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 8,
    },
    {
      id: 'widget11',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-conversation-starts-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Conversation Starts' },
        value: { format: 'count' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 8,
    },
    {
      id: 'widget13',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-initiated-customer-hold-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Agent Initiated Customer Hold Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 1,
      row: 11,
    },
    {
      id: 'widget14',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-hold-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Agent Hold Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 11,
    },
    {
      id: 'widget15',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-hold-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Customer Hold Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 11,
    },
    {
      id: 'source-switcher1',
      type: 'source-switcher',
      entity: 'agent',
      presentation: { title: { show: true, text: 'Specific Agent' } },
      sizeX: 20,
      sizeY: 2,
      minSizeX: 10,
      minSizeY: 2,
      col: 1,
      row: 15,
    },
    {
      id: 'widget16',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-satisfaction-score',
        responseKey: 'percent',
        parameters: { 'resource-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'CSAT' },
        value: { format: 'percent' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 1,
      row: 17,
    },
    {
      id: 'widget17',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-talk-time',
        responseKey: 'avg',
        parameters: { 'resource-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Avg Talk Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 17,
    },
    {
      id: 'widget18',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-wrap-up-time',
        responseKey: 'avg',
        parameters: { 'resource-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Avg Wrap-up Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 17,
    },
    {
      id: 'widget19',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'work-accepted-count',
        responseKey: 'count',
        parameters: { 'resource-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Conversation Starts' },
        value: { format: 'count' },
        footer: { show: false, text: 'agents' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 17,
    },
    {
      id: 'widget21',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-initiated-customer-hold-time',
        responseKey: 'avg',
        parameters: { 'resource-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Avg Agent Initiated Customer Hold Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 1,
      row: 20,
    },
    {
      id: 'widget22',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'resource-hold-time',
        responseKey: 'avg',
        parameters: { 'resource-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Avg Agent Hold Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 6,
      row: 20,
    },
    {
      id: 'widget23',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-hold-time',
        responseKey: 'avg',
        parameters: { 'resource-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Avg Customer Hold Time' },
        value: { format: 'time' },
        footer: { show: false, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 11,
      row: 20,
    },
  ],
};
