import { DashboardSetting } from 'settings/types';

export const dashboardQueues: DashboardSetting = {
  id: 'queues-dashboard',
  name: 'Queues Dashboard',
  enabled: true,
  dropdownIndex: '20',
  widgets: [
    {
      id: 'title-widget1',
      type: 'label',
      presentation: { show: true, text: 'All Queues' },
      sizeX: 25,
      sizeY: 1,
      col: 7,
      row: 1,
    },
    {
      id: 'widget1',
      type: 'gauge',
      query: {
        api: 'realtime-statistics',
        endpoint: 'service-level',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: false, text: '' },
        value: { format: 'percent' },
        gaugeConfig: {
          data: {
            columns: [['data', 0]],
            type: 'gauge',
            colors: { data: '#777' },
          },
          gauge: {
            label: { show: false },
            units: '%',
            min: 0,
            max: 100,
          },
          tooltip: { show: false },
          color: {
            data: '#ffffff',
            pattern: ['#ff0000', '#f6c600', '#0aad36'],
            threshold: { values: [70, 80, 100] },
          },
          size: { height: 156 },
          bindto: '#chart-widget1',
        },
        footer: { show: true, text: 'Answered within SLA' },
      },
      sizeX: 8,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 8,
      row: 3,
    },
    {
      id: 'widget2',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-satisfaction-score',
        responseKey: 'percent',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'CSAT' },
        value: { format: 'percent' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 3,
    },
    {
      id: 'widget3',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-length',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'In Queue' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 6,
    },
    {
      id: 'widget4',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Queue Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 3,
    },
    {
      id: 'widget5',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'max',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Max Wait Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 6,
    },
    {
      id: 'widget6',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandons-count',
        responseKey: 'count',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Abandons' },
        value: { format: 'count' },
        footer: { show: true, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 26,
      row: 3,
    },
    {
      id: 'widget7',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandon-time',
        responseKey: 'avg',
        parameters: {},
      },
      presentation: {
        header: { show: true, text: 'Avg Abandon Time' },
        value: { format: 'time' },
        footer: { show: true, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 26,
      row: 6,
    },
    {
      id: 'source-switcher1',
      type: 'source-switcher',
      entity: 'queue',
      presentation: { title: { show: true, text: 'Queue' } },
      sizeX: 25,
      sizeY: 2,
      minSizeX: 10,
      minSizeY: 2,
      col: 7,
      row: 10,
      selectedValue: 'all',
    },
    {
      id: 'widget8',
      type: 'gauge',
      query: {
        api: 'realtime-statistics',
        endpoint: 'service-level',
        responseKey: 'percent',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: false, text: '' },
        value: { format: 'percent' },
        gaugeConfig: {
          data: {
            columns: [['data', 0]],
            type: 'gauge',
            colors: { data: '#777' },
          },
          gauge: {
            label: { show: false },
            units: '%',
            min: 0,
            max: 100,
          },
          tooltip: { show: false },
          color: {
            data: '#ffffff',
            pattern: ['#ff0000', '#f6c600', '#0aad36'],
            threshold: { values: [70, 80, 100] },
          },
          size: { height: 156 },
          bindto: '#chart-widget8',
        },
        footer: { show: true, text: 'Answered within SLA' },
      },
      sizeX: 8,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 8,
      row: 12,
    },
    {
      id: 'widget9',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-satisfaction-score',
        responseKey: 'percent',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'CSAT' },
        value: { format: 'percent' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 12,
    },
    {
      id: 'widget10',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-length',
        responseKey: 'count',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'In Queue' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 15,
    },
    {
      id: 'widget11',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'avg',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Avg Queue Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 12,
    },
    {
      id: 'widget12',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'max',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Max Wait Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 15,
    },
    {
      id: 'widget13',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandons-count',
        responseKey: 'count',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Abandons' },
        value: { format: 'count' },
        footer: { show: true, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 26,
      row: 12,
    },
    {
      id: 'widget14',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandon-time',
        responseKey: 'avg',
        parameters: { 'queue-id': 'source-switcher1' },
      },
      presentation: {
        header: { show: true, text: 'Avg Abandon Time' },
        value: { format: 'time' },
        footer: { show: true, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 26,
      row: 15,
    },
    {
      id: 'source-switcher2',
      type: 'source-switcher',
      entity: 'queue',
      presentation: { title: { show: true, text: 'Queue' } },
      sizeX: 25,
      sizeY: 2,
      minSizeX: 10,
      minSizeY: 2,
      col: 7,
      row: 19,
      selectedValue: 'all',
    },
    {
      id: 'widget15',
      type: 'gauge',
      query: {
        api: 'realtime-statistics',
        endpoint: 'service-level',
        responseKey: 'percent',
        parameters: { 'queue-id': 'source-switcher2' },
      },
      presentation: {
        header: { show: false, text: '' },
        value: { format: 'percent' },
        gaugeConfig: {
          data: {
            columns: [['data', 0]],
            type: 'gauge',
            colors: { data: '#777' },
          },
          gauge: {
            label: { show: false },
            units: '%',
            min: 0,
            max: 100,
          },
          tooltip: { show: false },
          color: {
            data: '#ffffff',
            pattern: ['#ff0000', '#f6c600', '#0aad36'],
            threshold: { values: [70, 80, 100] },
          },
          size: { height: 156 },
          bindto: '#chart-widget15',
        },
        footer: { show: true, text: 'Answered within SLA' },
      },
      sizeX: 8,
      sizeY: 6,
      minSizeX: 5,
      minSizeY: 3,
      col: 8,
      row: 21,
    },
    {
      id: 'widget16',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'customer-satisfaction-score',
        responseKey: 'percent',
        parameters: { 'queue-id': 'source-switcher2' },
      },
      presentation: {
        header: { show: true, text: 'CSAT' },
        value: { format: 'percent' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 21,
    },
    {
      id: 'widget17',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-length',
        responseKey: 'count',
        parameters: { 'queue-id': 'source-switcher2' },
      },
      presentation: {
        header: { show: true, text: 'In Queue' },
        value: { format: 'count' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 16,
      row: 24,
    },
    {
      id: 'widget18',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'avg',
        parameters: { 'queue-id': 'source-switcher2' },
      },
      presentation: {
        header: { show: true, text: 'Avg Queue Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 21,
    },
    {
      id: 'widget19',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-time',
        responseKey: 'max',
        parameters: { 'queue-id': 'source-switcher2' },
      },
      presentation: {
        header: { show: true, text: 'Max Wait Time' },
        value: { format: 'time' },
        footer: { show: false, text: '' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 21,
      row: 24,
    },
    {
      id: 'widget20',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandons-count',
        responseKey: 'count',
        parameters: { 'queue-id': 'source-switcher2' },
      },
      presentation: {
        header: { show: true, text: 'Abandons' },
        value: { format: 'count' },
        footer: { show: true, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 26,
      row: 21,
    },
    {
      id: 'widget21',
      type: 'statistic',
      query: {
        api: 'realtime-statistics',
        endpoint: 'queue-abandon-time',
        responseKey: 'avg',
        parameters: { 'queue-id': 'source-switcher2' },
      },
      presentation: {
        header: { show: true, text: 'Avg Abandon Time' },
        value: { format: 'time' },
        footer: { show: true, text: 'Voice Only' },
      },
      sizeX: 5,
      sizeY: 3,
      minSizeX: 5,
      minSizeY: 3,
      col: 26,
      row: 24,
    },
  ],
};
