name: Deploy Frontend
on:
  repository_dispatch:
  schedule:
    - cron: '5 12 * * 0'
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: yarn install
        run: |
          npm i yarn -g

      - name: install yarn deps
        run: |
          yarn install --frozen-lockfile

      - name: have webpack build the app
        run: |
          yarn build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy files to the dev website with the AWS CLI
      run: |
        aws s3 sync ./packages/wfm/build s3://cx-wfm-dev