name: Deploy Frontend
on:
  repository_dispatch:
  schedule:
    - cron: '5 12 * * 0'
jobs:
  setup:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: yarn install
        run: |
          npm i yarn -g
  dependencies:
    name: install yarn dependencies
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: install yarn deps
        run: |
          yarn install --frozen-lockfile
  build:
    name: build the app
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: have webpack build the app
        run: |
          npm run build
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy files to the dev website with the AWS CLI
      run: |
        aws s3 sync ./packages/wfm/build s3://cx-wfm-dev